/* HEPGEN Autogenerated from file => trace_data.txt */
var rand = function(maximum,minimum){
	return Math.floor(Math.random() * (maximum - minimum + 1)) + minimum;
}

var randomByte = function() {
return Math.round(Math.random()*256);
}

var randomIp = function() {
var ip = randomByte() +'.' +
	   randomByte() +'.' +
	   randomByte() +'.' +
	   randomByte();
if (isPrivate(ip)) return randomIp();
return ip;
}

var isPrivate = function(ip) {
return /^10\.|^192\.168\.|^172\.16\.|^172\.17\.|^172\.18\.|^172\.19\.|^172\.20\.|^172\.21\.|^172\.22\.|^172\.23\.|^172\.24\.|^172\.25\.|^172\.26\.|^172\.27\.|^172\.28\.|^172\.29\.|^172\.30\.|^172\.31\./.test(ip);
}


var call_id = Math.random().toString(36).substring(7) + '@127.0.0.1';
var callee = rand(101,199);
var domain = 'sipcapture.org';
var priv_ip = '192.168.10.'+rand(10,200);
var priv_nat = randomIp();
var pub_ip = randomIp();

var useragent = 'HEPGEN.JS@sipcapture.org';

var config = { 
	NAME:"HEPGEN Registration with Auth",
	HEP_SERVER:"127.0.0.1",
	HEP_PORT:9060,
	HEP_ID:"2001",
	HEP_AUTH:"myHep",
	MESSAGES: [ 
		{
			rcinfo:{ 
				type:"HEP",
				version:3,
				payload_type:1,
				captureId:"2001",
				capturePass:"myHep",
				ip_family:2,
				protocol:6,
				proto_type:1,
				srcIp:priv_nat,
				dstIp:pub_ip,
				srcPort:5060,
				dstPort:5060,
			},
			pause:100,
			payload:"REGISTER sip:" + domain + " SIP/2.0\r\nVia: SIP/2.0/TCP " + priv_ip + ":10573;branch=d1zhpz9hG4bK-524287-1---54496c7e22d61208;rport\r\nMax-Forwards: 70\r\nContact: <sip:" + callee + "@127.0.0.1:10573;transport=tcp>;+sip.instance=\"<urn:uuid:4ae5cab0-92ae-3add-b400-d4f3ed2ced37>\";reg-id=1\r\nTo: \"" + callee + "\"<sip:" + callee + "@" + domain + ">\r\nFrom: \"" + callee + "\"<sip:" + callee + "@" + domain + ">;tag=y6d07b1970340\r\nCall-ID: " + call_id + "\r\nCSeq: 1 REGISTER\r\nExpires: 300\r\nAllow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, REGISTER, SUBSCRIBE, INFO, PUBLISH, UPDATE\r\nSupported: replaces, answermode, eventlist, park-info, outbound, path\r\nUser-Agent: PortSIP UC Client  Android - v12.5.8\r\nAllow-Events: hold, talk, conference, dialog, park-info\r\nx-p-push: device-os=android;device-uid=d95LwAfORuSa-ygOP77i9k:APA91bG_w1_fUNUvWFPwUVMLuRRt0yIi0wg8xJj5dmZERgIAmj2n5dZjmGwevt59S_ETv9UNzxpe5cSK2p1XXjDi4SARCw2nLLTYPmz2wPfnX7pmlmnAvfvTB7ili5ZGoo-suO3dh3y1;allow-call-push=true;allow-message-push=true;app-id=com.portsip.portgo\r\nX-Push: device-os=android;device-uid=d95LwAfORuSa-ygOP77i9k:APA91bG_w1_fUNUvWFPwUVMLuRRt0yIi0wg8xJj5dmZERgIAmj2n5dZjmGwevt59S_ETv9UNzxpe5cSK2p1XXjDi4SARCw2nLLTYPmz2wPfnX7pmlmnAvfvTB7ili5ZGoo-suO3dh3y1;allow-call-push=true;allow-message-push=true;app-id=com.portsip.portgo\r\nContent-Length: 0\r\n\r\n\r\n",
		},
		{
			rcinfo:{ 
				type:"HEP",
				version:3,
				payload_type:1,
				captureId:"2001",
				capturePass:"myHep",
				ip_family:2,
				protocol:6,
				proto_type:1,
				srcIp:pub_ip,
				dstIp:priv_nat,
				srcPort:5060,
				dstPort:5060,
			},
			pause: rand(200,300),
			payload:"SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/TCP " + priv_ip + ":10573;branch=d1zhpz9hG4bK-524287-1---54496c7e22d61208;rport=5060;received=163.172.158.19\r\nFrom: \"" + callee + "\" <sip:" + callee + "@" + domain + ">;tag=y6d07b1970340\r\nTo: \"" + callee + "\" <sip:" + callee + "@" + domain + ">;tag=md2bi0UFXe9aprHXgp\r\nCall-ID: " + call_id + "\r\nCSeq: 1 REGISTER\r\nUser-Agent: QXIP\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE\r\nSupported: timer, path, replaces\r\nWWW-Authenticate: Digest realm=\"" + domain + "\", nonce=\"710c1526-8de2-4bde-b0bb-9bcda4f6cabf\", algorithm=MD5, qop=\"auth\"\r\nContent-Length: 0\r\n\r\n\r\n",
		},
		{
			rcinfo:{ 
				type:"HEP",
				version:3,
				payload_type:1,
				captureId:"2001",
				capturePass:"myHep",
				ip_family:2,
				protocol:6,
				proto_type:1,
				srcIp:priv_nat,
				dstIp:pub_ip,
				srcPort:5060,
				dstPort:5060,
			},
			pause: rand(100,1000),
			payload:"REGISTER sip:" + domain + " SIP/2.0\r\nVia: SIP/2.0/TCP " + priv_ip + ":10573;branch=hfoz8z9hG4bK-524287-1---a886ff35bbd74414;rport\r\nMax-Forwards: 70\r\nContact: <sip:" + callee + "@127.0.0.1:10573;transport=tcp>;+sip.instance=\"<urn:uuid:4ae5cab0-92ae-3add-b400-d4f3ed2ced37>\";reg-id=1\r\nTo: \"" + callee + "\"<sip:" + callee + "@" + domain + ">\r\nFrom: \"" + callee + "\"<sip:" + callee + "@" + domain + ">;tag=y6d07b1970340\r\nCall-ID: " + call_id + "\r\nCSeq: 2 REGISTER\r\nExpires: 300\r\nAllow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, REGISTER, SUBSCRIBE, INFO, PUBLISH, UPDATE\r\nSupported: replaces, answermode, eventlist, park-info, outbound, path\r\nUser-Agent: PortSIP UC Client  Android - v12.5.8\r\nAuthorization: Digest username=\"" + callee + "\",realm=\"" + domain + "\",nonce=\"710c1526-8de2-4bde-b0bb-9bcda4f6cabf\",uri=\"sip:" + domain + "\",response=\"627cd76e665cfd0c518d4b23d5759095\",cnonce=\"42b833b84c0401966bfab427f212e210\",nc=00000001,qop=auth,algorithm=MD5\r\nAllow-Events: hold, talk, conference, dialog, park-info\r\nx-p-push: device-os=android;device-uid=d95LwAfORuSa-ygOP77i9k:APA91bG_w1_fUNUvWFPwUVMLuRRt0yIi0wg8xJj5dmZERgIAmj2n5dZjmGwevt59S_ETv9UNzxpe5cSK2p1XXjDi4SARCw2nLLTYPmz2wPfnX7pmlmnAvfvTB7ili5ZGoo-suO3dh3y1;allow-call-push=true;allow-message-push=true;app-id=com.portsip.portgo\r\nX-Push: device-os=android;device-uid=d95LwAfORuSa-ygOP77i9k:APA91bG_w1_fUNUvWFPwUVMLuRRt0yIi0wg8xJj5dmZERgIAmj2n5dZjmGwevt59S_ETv9UNzxpe5cSK2p1XXjDi4SARCw2nLLTYPmz2wPfnX7pmlmnAvfvTB7ili5ZGoo-suO3dh3y1;allow-call-push=true;allow-message-push=true;app-id=com.portsip.portgo\r\nContent-Length: 0\r\n\r\n\r\n",
		},
		{
			rcinfo:{ 
				type:"HEP",
				version:3,
				payload_type:1,
				captureId:"2001",
				capturePass:"myHep",
				ip_family:2,
				protocol:6,
				proto_type:1,
				srcIp:pub_ip,
				dstIp:priv_nat,
				srcPort:5060,
				dstPort:5060,
			},
			pause:rand(100,10000),
			payload:"SIP/2.0 200 OK\r\nVia: SIP/2.0/TCP " + priv_ip + ":10573;branch=hfoz8z9hG4bK-524287-1---a886ff35bbd74414;rport=44403;received=163.172.158.19\r\nFrom: \"" + callee + "\" <sip:" + callee + "@" + domain + ">;tag=y6d07b1970340\r\nTo: \"" + callee + "\" <sip:" + callee + "@" + domain + ">;tag=di13o148Ng4USNtK3H\r\nCall-ID: " + call_id + "\r\nCSeq: 2 REGISTER\r\nContact: <sip:" + callee + "@127.0.0.1:10573;transport=tcp>;expires=300\r\nDate: Fri, 23 Aug 2024 07:45:26 GMT\r\nUser-Agent: QXIP\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE\r\nSupported: timer, path, replaces\r\nContent-Length: 0\r\n\r\n\r\n",
		},
	]
};
module.exports = config;